version: '1.0'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/nginx3.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/cache:/data/nginx/cache
